### ISSUE TITLE
Rename min_lp_stake in assets to quantum

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/protos#245] opened 2022-01-26 09:44 UTC
Cover this spec: https://github.com/vegaprotocol/specs-internal/pull/798/files

**Comment by gordsport** [comment] 2022-01-26 10:54
@jeremyletang - is this a duplicate of: https://github.com/vegaprotocol/vega/issues/4621

If so I will close the above and replace with this one

**Closed** 2022-01-27 10:30 UTC
